---
# Per environment values which override defaults in hmpps-prisoner-location/values.yaml

generic-service:
  ingress:
    host: prisoner-location.prison.service.justice.gov.uk

  env:
    INGRESS_URL: "https://prisoner-location.prison.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api.prison.service.justice.gov.uk"
    PRISONER_LOCATION_API_URL: "https://prisoner-location-api.prison.service.justice.gov.uk"

  allowlist:
    groups:
      - internal
      - offloc

generic-prometheus-alerts:
  elastiCacheAlertsClusterIds:
    cp-01c7fbb2bb05adc1-001: "HMPPS Prisoner Location ElastiCache Cluster Node 1"
    cp-01c7fbb2bb05adc1-002: "HMPPS Prisoner Location ElastiCache Cluster Node 2"
